Name:           ros-kinetic-turtlebot3-bringup
Version:        0.1.3
Release:        0%{?dist}
Summary:        ROS turtlebot3_bringup package

Group:          Development/Libraries
License:        Apache License 2.0
URL:            http://wiki.ros.org/turtlebot3_bringup
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-hls-lfcd-lds-driver
Requires:       ros-kinetic-robot-state-publisher
Requires:       ros-kinetic-rosserial-python
Requires:       ros-kinetic-turtlebot-teleop
Requires:       ros-kinetic-turtlebot3-description
BuildRequires:  ros-kinetic-catkin

%description
roslaunch scripts for starting the TurtleBot3

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Mon Apr 24 2017 Pyo <pyo@robotis.com> - 0.1.3-0
- Autogenerated by Bloom

